  
# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:

  build:

    runs-on: ubuntu-latest
    name: Run npm install and build

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install and build 
      run: |
        npm install
        npm run build --if-present
      env:
        CI: false
    - name: Deploy build
    - uses: jakejarvis/s3-sync-action@master
      with:
        args: --follow-symlinks --delete --exclude '.git/*' 
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        SOURCE_DIR: './build/'      # optional: defaults to entire repository

#   deploy:
#     runs-on: ubuntu-latest
#     name: Deploy app to dev environment
#     needs: build
#     steps:
#     - uses: actions/checkout@v2
#     - uses: jakejarvis/s3-sync-action@master
#       with:
#         args: --follow-symlinks --delete --exclude '.git/*' 
#       env:
#         AWS_REGION: 'eu-west-1'
#         AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
#         AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#         AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#         SOURCE_DIR: './build/'      # optional: defaults to entire repository
